import {useEffect,useState} from 'react';
import {Sun,Library,BookMarked,GraduationCap,Compass,Settings as SettingsIcon,Search,Plus,RefreshCw,ArrowUpRight,Bookmark,Check,FileText,Upload,ChevronRight,X,LoaderCircle,SlidersHorizontal,ThumbsUp,ThumbsDown,FolderOpen,NotebookPen,ExternalLink,BookOpen,History,Download} from 'lucide-react';
import {api,setToken,safeUrl,split} from './api';
import type {Paper,Direction,Course,Note} from './api';
import Reader from './Reader';
import Settings from './Settings';

const views=[['today','今日推荐',Sun],['classics','经典与必读',BookMarked],['library','我的论文库',Library],['courses','知识与课程',GraduationCap],['notes','阅读笔记',NotebookPen],['directions','研究方向',Compass],['settings','模型与设置',SettingsIcon],['jobs','更新记录',History]] as const;
const starters=[{name:'大模型与检索增强',description:'关注检索增强生成、证据可靠性与低成本复现。',keywords:['retrieval augmented generation','RAG','large language model'],categories:['cs.CL','cs.AI']},{name:'计算机视觉',description:'关注图像理解、视觉模型和可复现实验。',keywords:['computer vision','image recognition','visual learning'],categories:['cs.CV']},{name:'机器学习',description:'关注学习算法、模型训练与评估。',keywords:['machine learning','deep learning'],categories:['cs.LG']},{name:'数学与优化',description:'关注优化理论与算法。',keywords:['optimization','convex'],categories:['math.OC']}];
const blankDirection={id:'',name:'',description:'',keywords:[],excludes:[],categories:[],authors:[],venues:[]} as Direction;
const formatDate=(s:string)=>s?s.slice(0,10):'日期待补充';
export default function App(){
 const [boot,setBoot]=useState<any>();const [view,setView]=useState('today');const [directionId,setDirectionId]=useState(localStorage.getItem('direction')||'');
 const [papers,setPapers]=useState<Paper[]>([]);const [courses,setCourses]=useState<Course[]>([]);const [notes,setNotes]=useState<Note[]>([]);const [jobs,setJobs]=useState<any[]>([]);
 const [mode,setMode]=useState('recommended');const [query,setQuery]=useState('');const [courseQuery,setCourseQuery]=useState('');const [freeOnly,setFreeOnly]=useState(true);const [status,setStatus]=useState('');const [collection,setCollection]=useState('');
 const [selected,setSelected]=useState<Paper>();const [reader,setReader]=useState('');const [modal,setModal]=useState('');const [editing,setEditing]=useState<Direction>(blankDirection);
 const [toast,setToast]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState('');const [loading,setLoading]=useState(false);const [link,setLink]=useState('');const [searchSource,setSearchSource]=useState('arxiv');
 const [collectionText,setCollectionText]=useState('');const [courseForm,setCourseForm]=useState({title:'',url:'',tags:'',description:'',free:'待核验'});
 function notify(s:string){setToast(s);}
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),6000);return()=>clearTimeout(t);},[toast]);
 async function reload(){const b=await api('/bootstrap');setToken(b.token);setBoot(b);if(!b.directions.some((d:Direction)=>d.id===directionId)){const id=b.directions[0]?.id||'';setDirectionId(id);localStorage.setItem('direction',id);}}
 useEffect(()=>{reload().catch(e=>setError('无法连接后端：'+e.message));},[]);
 async function loadContent(){if(!boot)return;setLoading(true);try{if(['today','classics','library'].includes(view)){setPapers(await api('/papers?'+new URLSearchParams({view,direction_id:directionId,mode,q:query,status,collection})));}if(view==='courses')setCourses(await api('/courses?'+new URLSearchParams({direction_id:directionId,q:courseQuery,free_only:String(freeOnly)})));if(view==='notes')setNotes(await api('/notes'));if(view==='search')setPapers(await api('/search-results'));}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{const t=setTimeout(()=>loadContent(),150);return()=>clearTimeout(t);},[boot,view,directionId,mode,query,status,collection,courseQuery,freeOnly]);
 useEffect(()=>{if(!boot)return;let active=true;let last='';const poll=async()=>{try{const j=await api('/jobs');if(!active)return;setJobs(j);const sig=j[0]?.id+':'+j[0]?.status;if(last&&sig!==last&&['done','failed'].includes(j[0]?.status)){loadContent();notify(j[0].message);}last=sig;}catch{}};poll();const timer=setInterval(poll,3500);return()=>{active=false;clearInterval(timer);};},[!!boot,view,directionId,mode]);
 useEffect(()=>{function key(e:KeyboardEvent){if(e.key==='Escape'){setModal('');setSelected(undefined);}}window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 async function run(name:string,fn:()=>Promise<void>){if(busy)return;setBusy(name);setError('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 function nav(v:string){setReader('');setView(v);setQuery('');setStatus('');setCollection('');setSelected(undefined);setError('');setMode(v==='classics'?'personal':'recommended');}
 async function patch(p:Paper,values:any){await api('/papers/'+p.id,'PATCH',values);await loadContent();if(selected?.id===p.id)setSelected({...selected,...values});await reload();}
 async function openDetails(p:Paper){setSelected(p);setCollectionText(p.collections?.join(', ')||'');}
 function openReader(p:Paper){setSelected(undefined);setReader(p.id);}
 async function saveDirection(d:Direction){const saved=await api('/directions','POST',d);await reload();setDirectionId(saved.id);localStorage.setItem('direction',saved.id);setModal('');notify('研究方向已保存，可以获取论文了');}
 async function update(){await api('/jobs','POST',{direction_id:directionId});setJobs(await api('/jobs'));notify('已开始获取论文，进度可在更新记录中查看');}
 const direction:Direction|undefined=boot?.directions.find((d:Direction)=>d.id===directionId);
 const activeJob=jobs.find(j=>['running','queued'].includes(j.status));
 const allCollections=Array.from(new Set(papers.flatMap(p=>p.collections||[])));
 function card(p:Paper){const excluded=!!p.excluded?.length;return <article className={'paper-card '+(excluded?'filtered':'')} key={p.id}><div className="paper-content">{view==='classics'&&p.classic_rank&&<div className="classic-ranking"><strong>#{p.classic_rank}</strong><span className={'grade grade-'+p.classic_grade}>{p.classic_grade} 级</span><b>{p.classic_score?.toFixed(1)} <small>/ 100 阅读优先分</small></b><span className="muted">{p.score_scope==='personal'?'我的方向榜':'全部精选榜'}</span></div>}<div className="meta"><span className={'pill '+(p.classic?'warm':'')}>{p.classic?'经典 / 延伸阅读':p.source}</span><span>{formatDate(p.published)}</span>{p.pdf_file&&<span className="file-state"><FileText size={13}/>PDF 已保存</span>}{p.status!=='未读'&&<span>{p.status}</span>}</div><button className="paper-title" onClick={()=>openDetails(p)}>{p.title}</button><div className="authors">{p.authors.slice(0,3).join(' · ')}{p.authors.length>3?' 等':''}</div><p className="paper-abstract">{p.analysis?.summary||p.summary?.text||p.curation||p.abstract||'暂无摘要，可更新元数据或上传 PDF 后解读。'}</p>{(p.reasons?.length||excluded)&&<div className={'reason '+(excluded?'excluded':'')}><span>{excluded?'筛除依据':'推荐依据'}</span>{excluded?p.excluded!.join('；'):p.reasons?.join('；')}</div>}{view==='classics'&&p.score_parts&&<details className="score-explanation"><summary>查看评分依据</summary><p>来源依据 {p.score_parts.evidence}/40 · 时间积累 {p.score_parts.maturity}/20{p.score_scope==='personal'?` · 方向匹配 ${p.score_parts.relevance}/40`:'；全部榜按前两项合计 / 60 换算为百分制。'}</p><p>等级：S ≥ 90，A ≥ 75，B ≥ 60，C &lt; 60。分数用于安排阅读顺序，不代表学术质量或权威评级。</p></details>}{p.classic&&<div className="evidence">{p.evidence.map((e,i)=><a key={i} href={safeUrl(e.url)} target="_blank" rel="noreferrer">{e.type} · {e.label} <ArrowUpRight size={12}/></a>)}</div>}<div className="tags">{p.tags.slice(0,4).map(t=><span key={t}>{t}</span>)}</div></div><div className="paper-footer"><div className="row"><button className="primary" onClick={()=>openReader(p)}><BookOpen size={15}/>阅读与解读</button><button aria-label={(p.saved?'取消收藏 ':'收藏 ')+p.title} className={p.saved?'saved':''} disabled={!!busy} onClick={()=>run('save',()=>patch(p,{saved:!p.saved}))}>{p.saved?<Check size={15}/>:<Bookmark size={15}/>} {p.saved?'已收藏':'收藏'}</button><button className="text-button" onClick={()=>run('later',()=>patch(p,{saved:true,status:'稍后读'}))}>稍后读</button></div><div className="row feedback"><button className={'icon-button '+(p.feedback==='helpful'?'saved':'')} aria-label="这篇有帮助" onClick={()=>run('feedback',()=>patch(p,{feedback:p.feedback==='helpful'?'':'helpful'}))}><ThumbsUp size={15}/></button><button className={'icon-button '+(p.feedback==='irrelevant'?'negative':'')} aria-label="这篇不相关" onClick={()=>run('feedback',()=>patch(p,{feedback:p.feedback==='irrelevant'?'':'irrelevant'}))}><ThumbsDown size={15}/></button>{excluded&&<button onClick={()=>run('keep',()=>patch(p,{feedback:'keep',saved:true}))}>保留到论文库</button>}</div></div></article>;}
 return <div className="app-shell"><aside className="sidebar"><a className="brand" href="#" onClick={e=>{e.preventDefault();nav('today');}}><span className="brand-mark"><BookOpen size={23}/></span><span>知阅<small>PAPERNEST</small></span></a><span className="nav-label">研究工作台</span><nav>{views.map(([id,label,Icon])=><button key={id} className={view===id&&!reader?'nav-item active':'nav-item'} onClick={()=>nav(id)}><Icon size={18}/>{label}{id==='library'&&<span className="nav-count">{boot?.counts.saved||0}</span>}</button>)}</nav><div className="sidebar-bottom"><span className="nav-label">当前研究方向</span><p>{direction?.name||'尚未设置'}</p><button className="text-button" onClick={()=>nav('directions')}>管理研究方向 <ChevronRight size={14}/></button><div className="local-status"><span/>本地空间 · 资料保存在本机</div></div></aside>
 <div className="workspace"><header className="topbar"><div className="breadcrumb">个人研究空间 <ChevronRight size={13}/><span>{reader?'论文阅读':views.find(v=>v[0]===view)?.[1]||'论文搜索'}</span></div><div className="row"><select className="direction-picker" aria-label="当前研究方向" value={directionId} onChange={e=>{setDirectionId(e.target.value);localStorage.setItem('direction',e.target.value);}}><option value="">选择研究方向</option>{boot?.directions.map((d:Direction)=><option key={d.id} value={d.id}>{d.name}</option>)}</select><button className="icon-button" aria-label="搜索论文" onClick={()=>{setLink('');setModal('search');}}><Search size={19}/></button><span className="avatar">我</span></div></header>
 <main className={'main '+(reader?'reader-main':'')}>
 {error&&<div className="alert" role="alert">{error}<button className="icon-button" aria-label="关闭提示" onClick={()=>setError('')}><X size={16}/></button></div>}
 {!boot?<div className="empty"><LoaderCircle className="spin"/>正在连接本地工作台…</div>:reader?<Reader key={reader} id={reader} directionId={directionId} back={()=>{setReader('');loadContent();}} notify={notify} courses={q=>{setReader('');setView('courses');setCourseQuery(q);}}/>:<>
 {view==='today'&&<><div className="page-heading"><div><span className="eyebrow">YOUR DAILY READING</span><h1>今日，值得读的论文。</h1><p>{direction?`围绕「${direction.name}」整理，每天最多 ${boot.settings.daily_limit} 篇。`:'先告诉知阅你的研究方向，开始建立每天的阅读清单。'}</p></div><button className="primary" disabled={!!busy||!!activeJob||!direction} onClick={()=>run('update',update)}><RefreshCw size={16} className={activeJob?'spin':''}/>{activeJob?'正在获取':'获取最新论文'}</button></div>
 {!direction?<section className="onboarding"><span className="eyebrow">START WITH A QUESTION</span><h2>你正在研究什么？</h2><p>选一个方向作为起点，再补充具体需求。推荐会随你的反馈调整。</p><div className="starter-grid">{starters.map(d=><button key={d.name} onClick={()=>{setEditing({...blankDirection,...d});setModal('direction');}}><Compass size={21}/><strong>{d.name}</strong><span>{d.description}</span><ArrowUpRight size={16}/></button>)}</div><button className="text-button" onClick={()=>{setEditing(blankDirection);setModal('direction');}}><Plus size={16}/>其他学科 / 自定义方向</button></section>:<><div className="topic-banner"><div><span className="pill">研究画像</span><p>{direction.description||direction.keywords.join(' · ')}</p></div><button className="text-button" onClick={()=>{setEditing(direction);setModal('direction');}}><SlidersHorizontal size={15}/>调整</button></div>{activeJob&&<div className="task-banner"><LoaderCircle size={16} className="spin"/>{activeJob.message}<button className="text-button" onClick={()=>nav('jobs')}>查看进度</button></div>}<div className="list-toolbar"><div className="tabs">{[['recommended','每日精选'],['all','全部候选'],['filtered','被过滤的论文']].map(([k,v])=><button key={k} className={mode===k?'active':''} onClick={()=>setMode(k)}>{v}</button>)}</div><span className="muted">最近 {boot.settings.lookback_days} 天 · {papers.length} 篇</span></div>{loading?<div className="loading-line">正在整理…</div>:papers.length?papers.map(card):<div className="empty"><Sun size={32}/><h3>{mode==='recommended'?'暂时没有符合条件的新论文':'这里还没有论文'}</h3><p>点击“获取最新论文”，或调整方向关键词。没有足够相关论文时，不凑数。</p><button onClick={()=>nav('classics')}>先看看经典与基础阅读</button></div>}<div className="muted caption">{boot.settings.auto_ai?'已启用 AI 候选精筛；未完成时保留规则结果。':'当前使用关键词与规则排序。可在设置中启用 AI 精筛。'}推荐依据不等同于质量保证。</div></>}</>}
 {view==='classics'&&<><div className="page-heading"><div><span className="eyebrow">FOUNDATIONS & ESSENTIALS</span><h1>读懂一个方向的来路。</h1><p>从有来源的基础论文开始，再找到与你课题直接相关的必读工作。</p></div></div><div className="list-toolbar"><div className="tabs"><button className={mode==='personal'?'active':''} onClick={()=>setMode('personal')}>我的方向排行榜</button><button className={mode==='all'?'active':''} onClick={()=>setMode('all')}>全部精选排行榜</button></div><span className="muted">{papers.length} / 100 篇 · 按阅读优先分排序</span></div>{loading?<div className="loading-line">正在整理排行榜…</div>:papers.length?papers.map(card):<div className="empty"><BookMarked size={32}/><h3>该方向的精选清单还在积累</h3><p>当前内置 100 篇计算机与机器学习精选及教材延伸阅读。你可以调整方向，或导入论文并附上依据加入清单。</p><button onClick={()=>setMode('all')}>浏览全部精选</button></div>}<p className="muted caption">每榜最多 100 篇，不足时不凑数。我的方向榜：方向匹配 40 分 + 来源依据 40 分 + 时间积累 20 分；全部榜不使用方向匹配，将后两项换算为百分制。同分按发表时间、条目 ID 排序。未选择方向时显示全部榜。教材收录是阅读线索，不等于必读认证。</p></>}
 {view==='library'&&<><div className="page-heading"><div><span className="eyebrow">YOUR RESEARCH COLLECTION</span><h1>我的论文库</h1><p>保存每一篇值得回来的论文，以及你自己的理解。</p></div><div className="row"><button onClick={()=>{setLink('');setModal('import');}}><Upload size={16}/>导入论文</button><a className="button" href="/api/export/citations?format=bibtex"><Download size={15}/>BibTeX</a><a className="button" href="/api/export/citations?format=ris">RIS</a></div></div><div className="list-toolbar"><div className="search-field"><Search size={17}/><input aria-label="搜索论文库" placeholder="搜索标题、作者、正文或笔记…" value={query} onChange={e=>setQuery(e.target.value)}/></div><select aria-label="阅读状态筛选" value={status} onChange={e=>setStatus(e.target.value)}><option value="">全部阅读状态</option>{['稍后读','正在读','已读','未读'].map(x=><option key={x}>{x}</option>)}</select><select aria-label="专题筛选" value={collection} onChange={e=>setCollection(e.target.value)}><option value="">全部专题</option>{allCollections.map(x=><option key={x}>{x}</option>)}</select></div>{papers.length?papers.map(card):<div className="empty"><FolderOpen size={34}/><h3>把第一篇论文放进来</h3><p>从每日推荐中收藏，或导入 DOI、arXiv 链接与本地 PDF。</p><button className="primary" onClick={()=>setModal('import')}>导入论文</button></div>}</>}
 {view==='courses'&&<><div className="page-heading"><div><span className="eyebrow">LEARN WHAT YOU NEED</span><h1>补上知识，再往前一步。</h1><p>围绕研究方向与论文前置知识，优先推荐免费课程和学习材料。</p></div><button onClick={()=>setModal('course')}><Plus size={16}/>添加课程链接</button></div><div className="list-toolbar"><div className="search-field"><Search size={17}/><input value={courseQuery} onChange={e=>setCourseQuery(e.target.value)} placeholder="知识点、课程名，例如 attention" aria-label="搜索课程"/></div><label className="check"><input type="checkbox" checked={freeOnly} onChange={e=>setFreeOnly(e.target.checked)}/>免费优先（仅显示已标注免费）</label><a className="button" target="_blank" rel="noreferrer" href={'https://search.bilibili.com/all?keyword='+encodeURIComponent((courseQuery||direction?.name||'计算机')+' 公开课')}>B 站搜索 <ArrowUpRight size={14}/></a></div><p className="muted caption">B 站按钮是站内搜索入口；下方卡片是收录资源，课程费用与访问条件以来源页面为准。</p><div className="course-grid">{courses.map(c=><article className="course-card" key={c.id}><div className="meta"><span className="pill">{c.free}</span><span>{c.language} · {c.level}</span></div><span className="course-platform">{c.platform}</span><h3><a href={safeUrl(c.url)} target="_blank" rel="noreferrer">{c.title}<ArrowUpRight size={15}/></a></h3><div className="authors">{c.author}</div><p>{c.description}</p><div className="course-reason">{c.reason}</div><div className="tags">{c.tags.slice(0,4).map(t=><button key={t} onClick={()=>setCourseQuery(t)}>{t}</button>)}</div><div className="row spread"><select aria-label={c.title+' 学习状态'} value={c.status} onChange={e=>run('course-status',async()=>{await api('/courses/'+c.id,'PATCH',{status:e.target.value});await loadContent();})}>{['未学习','待学习','学习中','已完成'].map(x=><option key={x}>{x}</option>)}</select><button className="icon-button" aria-label={c.saved?'取消课程收藏':'收藏课程'} onClick={()=>run('course-save',async()=>{await api('/courses/'+c.id,'PATCH',{saved:!c.saved});await loadContent();})}>{c.saved?<Check size={17}/>:<Bookmark size={17}/>}</button></div>{c.verified&&<small>来源核验 {c.verified}</small>}</article>)}</div>{!courses.length&&<div className="empty"><GraduationCap size={32}/><h3>还没有匹配的收录课程</h3><p>可以调整关键词、取消免费筛选，或添加已知课程链接。</p></div>}</>}
 {view==='directions'&&<><div className="page-heading"><div><span className="eyebrow">RESEARCH PROFILE</span><h1>你的问题，决定推荐方向。</h1><p>关键词用于检索；具体研究需求用于 AI 判断相关性。</p></div><button className="primary" onClick={()=>{setEditing(blankDirection);setModal('direction');}}><Plus size={16}/>新建方向</button></div><div className="direction-grid">{boot.directions.map((d:Direction)=><article className="settings-section" key={d.id}><div className="row spread"><h2>{d.name}</h2>{d.id===directionId&&<span className="pill">当前方向</span>}</div><p>{d.description}</p><div className="tags">{d.keywords.map(t=><span key={t}>{t}</span>)}</div><p className="muted">排除：{d.excludes.join('、')||'未设置'}</p><div className="row"><button onClick={()=>{setEditing(d);setModal('direction');}}>编辑</button><button onClick={()=>{setDirectionId(d.id);localStorage.setItem('direction',d.id);nav('today');}}>查看推荐</button><button className="text-button danger" onClick={()=>{setEditing(d);setModal('delete-direction');}}>删除方向</button></div></article>)}</div>{!boot.directions.length&&<div className="empty"><Compass size={32}/><h3>先添加一个研究方向</h3><p>可以精确到方法或研究问题，例如“低资源中文问答”。</p></div>}</>}
 {view==='notes'&&<><div className="page-heading"><div><span className="eyebrow">THINKING IN THE MARGINS</span><h1>阅读笔记</h1><p>把论文中的线索，变成自己的研究想法。</p></div><a className="button" href="/api/export/notes">导出 Markdown</a></div>{notes.map(n=><article className="note large" key={n.id}><div className="row spread"><button className="text-button" onClick={()=>setReader(n.paper_id)}>{n.paper_title||"打开论文"} · 第 {n.page||1} 页 <ArrowUpRight size={14}/></button><span className="muted">{formatDate(n.created)}</span></div>{n.quote&&<blockquote>{n.quote}</blockquote>}<p>{n.text}</p></article>)}{!notes.length&&<div className="empty"><NotebookPen size={32}/><h3>你的想法会留在这里</h3><p>阅读时选中一段文字，保存高亮或记下笔记。</p></div>}</>}
 {view==='settings'&&<Settings notify={notify} reload={reload}/>}
 {view==='jobs'&&<><div className="page-heading"><div><span className="eyebrow">SOURCE ACTIVITY</span><h1>更新记录</h1><p>查看来源状态、候选获取范围和未完成的任务。</p></div><button disabled={!!activeJob||!!busy||!direction} onClick={()=>run('update',update)}><RefreshCw size={16}/>重新获取</button></div>{jobs.map(j=><article className="job-card" key={j.id}><div className="row spread"><h3>{j.kind}</h3><span className={'pill '+(j.status==='failed'?'error-pill':'')}>{({queued:'等待执行',running:'运行中',done:'已完成',failed:'失败',interrupted:'已中断'} as any)[j.status]}</span></div><p>{j.message}</p>{j.warnings.map((w:string,i:number)=><p className="warning" key={i}>{w}</p>)}<small>{new Date(j.created).toLocaleString()}</small></article>)}{!jobs.length&&<div className="empty"><History size={32}/><h3>还没有获取记录</h3><p>添加方向后，点击获取最新论文。</p></div>}</>}
 {view==='search'&&<><div className="page-heading"><div><span className="eyebrow">EXPLORE PAPERS</span><h1>搜索与最近收录</h1><p>手动搜索的结果保留在候选库中，收藏后进入个人论文库。</p></div><button onClick={()=>setModal('search')}><Search size={16}/>搜索来源</button></div>{activeJob&&<div className="task-banner"><LoaderCircle className="spin" size={16}/>{activeJob.message}</div>}{papers.map(card)}</>}
 </>}
 </main><footer className="footer">知阅 PaperNest <span>本地个人研究工作台 · 原文可核对，推荐有依据</span></footer></div>
 {toast&&<div className="toast" role="status"><Check size={16}/>{toast}<button className="icon-button" aria-label="关闭消息" onClick={()=>setToast('')}><X size={15}/></button></div>}
 {busy&&<div className="working" role="status"><LoaderCircle className="spin" size={16}/>正在处理…</div>}
 {selected&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(undefined);}}><section className="dialog detail-dialog" role="dialog" aria-modal="true" aria-label="论文详情"><div className="row spread"><span className="eyebrow">PAPER DETAILS</span><button className="icon-button" aria-label="关闭详情" onClick={()=>setSelected(undefined)}><X/></button></div><h2>{selected.title}</h2><div className="meta">{selected.authors.join(' · ')}</div><div className="row"><button className="primary" onClick={()=>openReader(selected)}><BookOpen size={16}/>阅读与解读</button>{selected.url&&<a className="button" target="_blank" rel="noreferrer" href={safeUrl(selected.url)}>原始来源 <ExternalLink size={14}/></a>}<button disabled={!!busy} onClick={()=>run('metadata',async()=>{const p=await api<Paper>('/papers/'+selected.id+'/metadata','POST');setSelected(p);await loadContent();notify('元数据已更新');})}>更新摘要</button></div><h3>作者摘要</h3><p className="abstract">{selected.abstract||'尚无摘要，可以尝试更新元数据。'}</p>{selected.analysis&&<><h3>AI 推荐理由</h3><p>{selected.analysis.reason}</p><small>未确认：{selected.analysis.uncertain}</small></>}{selected.evidence?.length>0&&<><h3>精选依据</h3>{selected.evidence.map((e,i)=><p key={i}><a href={safeUrl(e.url)} target="_blank" rel="noreferrer">{e.label} ↗</a></p>)}</>}
 <label className="field">专题集合（逗号分隔）<div className="row"><input value={collectionText} onChange={e=>setCollectionText(e.target.value)} placeholder="我的课题, 综述写作"/><button disabled={!!busy} onClick={()=>run('collection',()=>patch(selected,{collections:split(collectionText),saved:true}))}>保存</button></div></label><div className="row"><button disabled={!!busy} onClick={()=>run('zotero',async()=>{const result=await api('/papers/'+selected.id+'/zotero','POST',{collection:boot.settings.zotero_collection,include_pdf:boot.settings.zotero_pdf});notify(result.messages.join('；'));})}>保存到 Zotero</button><a className="button" href={'/api/export/citations?paper_id='+selected.id}>导出引用</a><button disabled={!!busy||!selected.pdf_url} onClick={()=>run('download',async()=>{await api('/papers/'+selected.id+'/download','POST');setSelected(await api('/papers/'+selected.id));await loadContent();notify('PDF 已保存到本机');})}>保存 PDF</button><button onClick={()=>setModal('classic')}>加入经典清单</button></div>{error&&<div className="alert">{error}</div>}</section></div>}
 {modal&&<div className="overlay modal-top" onMouseDown={e=>{if(e.target===e.currentTarget)setModal('');}}><section className="dialog" role="dialog" aria-modal="true" aria-label="编辑"><div className="row spread"><h2>{{direction:editing.id?'编辑研究方向':'添加研究方向',import:'导入论文',search:'搜索论文来源',course:'添加课程资源',classic:'添加精选依据','delete-direction':'删除方向'}[modal]}</h2><button className="icon-button" aria-label="关闭" onClick={()=>setModal('')}><X/></button></div>
 {error&&<div className="alert" role="alert">{error}</div>}
 {modal==='direction'&&<form onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);run('direction',()=>saveDirection({...editing,keywords:split(String(form.get('keywords')||'')),excludes:split(String(form.get('excludes')||'')),categories:split(String(form.get('categories')||'')),authors:split(String(form.get('authors')||'')),venues:split(String(form.get('venues')||''))}));}}><label className="field">方向名称<input required value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})} placeholder="例如：检索增强生成"/></label><label className="field">具体研究需求<textarea value={editing.description} onChange={e=>setEditing({...editing,description:e.target.value})} placeholder="我关注什么问题？希望实现什么？有哪些资源限制？"/></label><label className="field">检索关键词（逗号分隔，优先填写英文术语）<input name="keywords" defaultValue={editing.keywords.join(', ')} onBlur={e=>setEditing({...editing,keywords:split(e.target.value)})} placeholder="retrieval augmented generation, RAG"/></label><label className="field">排除词（逗号分隔）<input name="excludes" defaultValue={editing.excludes.join(', ')} onBlur={e=>setEditing({...editing,excludes:split(e.target.value)})}/></label><label className="field">arXiv 分类（可选，逗号分隔）<input name="categories" defaultValue={editing.categories.join(', ')} onBlur={e=>setEditing({...editing,categories:split(e.target.value)})} placeholder="cs.CL, cs.AI；留空则不限制分类"/><small>支持其他学科，例如 math.OC、physics、q-bio。精准分类请参考 arXiv 分类表。</small></label><label className="field">关注作者（可选，逗号分隔）<input name="authors" defaultValue={editing.authors?.join(", ")||""} placeholder="填写论文署名中的英文姓名"/></label><label className="field">关注会议 / 期刊（可选）<input name="venues" defaultValue={editing.venues?.join(", ")||""} placeholder="例如 NeurIPS, ACL；用于已收录论文的偏好排序"/></label><button className="primary" disabled={!!busy}>保存研究方向</button></form>}
 {modal==='delete-direction'&&<><p>删除「{editing.name}」的配置和推荐记录，已收藏论文与笔记会保留。</p><button className="danger" disabled={!!busy} onClick={()=>run('delete-direction',async()=>{await api('/directions/'+editing.id,'DELETE');setModal('');await reload();})}>删除这个方向</button></>}
 {modal==='import'&&<><label className="field">DOI / arXiv 链接或编号<input value={link} onChange={e=>setLink(e.target.value)} placeholder="https://arxiv.org/abs/1706.03762"/></label><button className="primary" disabled={!!busy||!link.trim()} onClick={()=>run('import',async()=>{await api('/import/link','POST',{url:link});await reload();await loadContent();setModal('');notify('论文已加入个人论文库');})}>导入论文信息</button><div className="divider"/><label className="upload-zone"><Upload size={26}/><strong>选择本地 PDF，可批量导入</strong><span>每个文件最多 40 MB · 扫描件需另行 OCR</span><input type="file" accept=".pdf" multiple hidden onChange={e=>{const files=Array.from(e.target.files||[]);run('upload',async()=>{for(const f of files){const fd=new FormData();fd.append('file',f);await api('/import/pdf','POST',fd);}await reload();await loadContent();setModal('');notify(`已导入 ${files.length} 个 PDF`);});}}/></label><label className="button">导入 BibTeX / RIS<input type="file" accept=".bib,.ris" hidden onChange={e=>{const f=e.target.files?.[0];if(f)run('citations',async()=>{const fd=new FormData();fd.append('file',f);const r=await api('/import/citations','POST',fd);await reload();await loadContent();setModal('');notify(`已导入 ${r.imported} 篇文献`);});}}/></label></>}
 {modal==='search'&&<form onSubmit={e=>{e.preventDefault();run('search',async()=>{await api('/jobs','POST',{query:link,source:searchSource,direction_id:directionId});setModal('');nav('search');setJobs(await api('/jobs'));});}}><label className="field">论文来源<select value={searchSource} onChange={e=>setSearchSource(e.target.value)}><option value="arxiv">arXiv</option><option value="openalex">OpenAlex</option></select></label><label className="field">检索词<input required value={link} onChange={e=>setLink(e.target.value)} placeholder="retrieval augmented generation"/></label><p className="muted">arXiv 支持分类与布尔表达式，如 cat:cs.CL AND all:retrieval。</p><button className="primary" disabled={!!busy||!!activeJob||!link.trim()}>开始搜索</button></form>}
 {modal==='course'&&<form onSubmit={e=>{e.preventDefault();run('course',async()=>{await api('/courses','POST',{...courseForm,tags:split(courseForm.tags)});setModal('');setFreeOnly(false);await loadContent();notify('课程已保存，费用状态以来源核验为准');});}}><label className="field">课程名称<input required value={courseForm.title} onChange={e=>setCourseForm({...courseForm,title:e.target.value})}/></label><label className="field">课程链接<input required type="url" value={courseForm.url} onChange={e=>setCourseForm({...courseForm,url:e.target.value})} placeholder="B 站视频、合集或课程官网链接"/></label><label className="field">关联知识点（逗号分隔）<input value={courseForm.tags} onChange={e=>setCourseForm({...courseForm,tags:e.target.value})}/></label><label className="field">费用状态<select value={courseForm.free} onChange={e=>setCourseForm({...courseForm,free:e.target.value})}>{['待核验','免费','部分免费','付费'].map(x=><option key={x}>{x}</option>)}</select></label><label className="field">推荐理由<textarea value={courseForm.description} onChange={e=>setCourseForm({...courseForm,description:e.target.value})}/></label><button className="primary" disabled={!!busy}>保存课程</button></form>}
 {modal==='classic'&&selected&&<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run('classic',async()=>{await patch(selected,{classic:true,curation:f.get('reason'),evidence:[...selected.evidence,{label:f.get('label'),url:f.get('url'),type:'个人核验'}]});setModal('');notify('已加入经典清单并保存来源');});}}><label className="field">入选理由<textarea required name="reason"/></label><label className="field">依据名称<input required name="label" placeholder="某课程书单 / 某篇综述"/></label><label className="field">依据链接<input required type="url" name="url"/></label><button className="primary" disabled={!!busy}>保存依据</button></form>}
 </section></div>}
 </div>;
}
