import {useEffect,useRef,useState} from 'react';
import * as pdfjs from 'pdfjs-dist';
import worker from 'pdfjs-dist/build/pdf.worker.min.mjs?url';
import 'pdfjs-dist/web/pdf_viewer.css';
import {ArrowLeft,ChevronLeft,ChevronRight,Languages,Highlighter,MessageCircle,NotebookPen,Download,BookOpen,LoaderCircle} from 'lucide-react';
import {api,safeUrl} from './api';
import type {Paper,Note,Summary} from './api';
pdfjs.GlobalWorkerOptions.workerSrc=worker;
type Props={id:string;directionId:string;back:()=>void;notify:(s:string)=>void;courses:(q:string)=>void};
export default function Reader({id,directionId,back,notify,courses}:Props){
 const [paper,setPaper]=useState<Paper>();const [page,setPage]=useState(1);const [pdf,setPdf]=useState<pdfjs.PDFDocumentProxy>();
 const [notes,setNotes]=useState<Note[]>([]);const [tab,setTab]=useState('summary');const [answer,setAnswer]=useState<Summary>();
 const [busy,setBusy]=useState('');const [error,setError]=useState('');const [quote,setQuote]=useState('');const [rects,setRects]=useState<Note['rects']>([]);
 const [note,setNote]=useState('');const [question,setQuestion]=useState('');const [zoom,setZoom]=useState(1);const [textMode,setTextMode]=useState(false);
 const [find,setFind]=useState('');const [findPages,setFindPages]=useState<number[]>([]);const [outline,setOutline]=useState<{title:string;page:number}[]>([]);
 const box=useRef<HTMLDivElement>(null);const canvas=useRef<HTMLCanvasElement>(null);const layer=useRef<HTMLDivElement>(null);const [width,setWidth]=useState(500);
 const pageReady=useRef(false);
 async function refresh(){const [p,n]=await Promise.all([api<Paper>('/papers/'+id),api<Note[]>('/notes?paper_id='+id)]);setPaper(p);setNotes(n);return p;}
 useEffect(()=>{let live=true;pageReady.current=false;refresh().then(p=>{if(live){setPage(p.read_page||1);pageReady.current=true;}}).catch(e=>setError(e.message));return()=>{live=false;};},[id]);
 useEffect(()=>{if(!paper?.pdf_file)return;let active=true;const loading=pdfjs.getDocument({url:'/api/papers/'+id+'/pdf',isEvalSupported:false});loading.promise.then(async doc=>{if(!active)return;setPdf(doc);const list=await doc.getOutline();const flat:{title:string;page:number}[]=[];async function walk(items:any[]){for(const item of items){try{const dest=typeof item.dest==='string'?await doc.getDestination(item.dest):item.dest;if(dest?.[0]){const index=typeof dest[0]==='number'?dest[0]:await doc.getPageIndex(dest[0]);flat.push({title:item.title,page:index+1});}if(item.items)await walk(item.items);}catch{}}}if(list)await walk(list);if(active)setOutline(flat);}).catch(e=>setError('PDF 加载失败：'+e.message));return()=>{active=false;loading.destroy();setPdf(undefined);};},[paper?.pdf_hash,id]);
 useEffect(()=>{if(!box.current)return;const ro=new ResizeObserver(entries=>setWidth(entries[0].contentRect.width));ro.observe(box.current);return()=>ro.disconnect();},[paper?.pdf_file,textMode]);
 useEffect(()=>{if(!pdf||!canvas.current||!layer.current||textMode)return;let stopped=false;let render:pdfjs.RenderTask|undefined;let tl:pdfjs.TextLayer|undefined;
  (async()=>{const p=await pdf.getPage(Math.min(page,pdf.numPages));if(stopped)return;const initial=p.getViewport({scale:1});const scale=(Math.max(width,200)/initial.width)*zoom;const viewport=p.getViewport({scale});const cv=canvas.current!;const ratio=window.devicePixelRatio||1;cv.width=viewport.width*ratio;cv.height=viewport.height*ratio;cv.style.width=viewport.width+'px';cv.style.height=viewport.height+'px';const l=layer.current!;l.replaceChildren();l.style.setProperty('--scale-factor',String(scale));l.style.width=viewport.width+'px';l.style.height=viewport.height+'px';render=p.render({canvasContext:cv.getContext('2d')!,viewport,transform:ratio!==1?[ratio,0,0,ratio,0,0]:undefined});await render.promise;if(stopped)return;tl=new pdfjs.TextLayer({textContentSource:await p.getTextContent(),container:l,viewport});await tl.render();})().catch(e=>{if(e.name!=='RenderingCancelledException'&&!stopped)setError('页面渲染失败，可切换文字阅读。');});return()=>{stopped=true;render?.cancel();tl?.cancel();};},[pdf,page,width,zoom,textMode]);
 useEffect(()=>{setQuote('');setRects([]);if(pageReady.current){const timer=setTimeout(()=>api('/papers/'+id,'PATCH',{read_page:page}).catch(()=>{}),500);return()=>clearTimeout(timer);}},[page,id]);
 async function action(name:string,fn:()=>Promise<void>){if(busy)return;setBusy(name);setError('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 function selected(){const sel=window.getSelection();if(!sel||!sel.rangeCount||!box.current?.contains(sel.anchorNode))return;const text=sel.toString().trim();if(!text)return;setQuote(text.slice(0,6000));const bound=layer.current?.getBoundingClientRect();if(bound&&!textMode){setRects(Array.from(sel.getRangeAt(0).getClientRects()).filter(r=>r.width&&r.height).map(r=>({x:(r.left-bound.left)/bound.width,y:(r.top-bound.top)/bound.height,w:r.width/bound.width,h:r.height/bound.height})));}else setRects([]);}
 async function ask(actionName:string,text:string){await action(actionName,async()=>{const result=await api<Summary>('/papers/'+id+'/ask','POST',{action:actionName,text,page});setAnswer(result);setTab('chat');});}
 async function saveNote(){await action('note',async()=>{await api('/notes','POST',{paper_id:id,text:note,quote,page,rects});setNote('');setQuote('');setRects([]);await refresh();setTab('notes');notify('笔记与选文已保存');});}
 function summaryText(s:Summary){return <><div className="meta"><span className="pill">{s.basis}</span><span>{s.provider} · {s.model}</span></div><div className="ai-text">{s.text.split(/(\[第\s*\d+\s*页\])/).map((part,i)=>{const m=part.match(/\[第\s*(\d+)\s*页\]/);return m?<button key={i} className="citation" onClick={()=>setPage(Math.min(Number(m[1]),pdf?.numPages||Number(m[1])))}>{part}</button>:<span key={i}>{part}</span>;})}</div></>;}
 if(!paper)return <div className="empty">{error||'正在打开论文…'}</div>;
 return <div className="reader"><div className="reader-heading"><button className="icon-button" onClick={back} aria-label="返回"><ArrowLeft/></button><div><span className="eyebrow">READING ROOM</span><h2>{paper.title}</h2></div><button onClick={()=>action('save',async()=>{await api('/papers/'+id,'PATCH',{saved:!paper.saved});await refresh();})}>{paper.saved?'已收藏':'收藏论文'}</button></div>
 <div className="reader-bar"><div className="row"><button className="icon-button" disabled={page<=1} onClick={()=>setPage(page-1)} aria-label="上一页"><ChevronLeft/></button><span>{page} / {pdf?.numPages||paper.pages?.length||'—'}</span><button className="icon-button" disabled={!pdf||page>=pdf.numPages} onClick={()=>setPage(page+1)} aria-label="下一页"><ChevronRight/></button><select aria-label="缩放比例" value={zoom} onChange={e=>setZoom(Number(e.target.value))}><option value={1}>适应宽度</option><option value={1.25}>125%</option><option value={1.5}>150%</option></select><button onClick={()=>setTextMode(!textMode)}>{textMode?'PDF 原文':'文字阅读'}</button></div><div className="row"><select aria-label="阅读状态" value={paper.status} onChange={e=>action('status',async()=>{await api('/papers/'+id,'PATCH',{status:e.target.value,saved:true});await refresh();})}>{['未读','稍后读','正在读','已读'].map(s=><option key={s}>{s}</option>)}</select>{paper.pdf_file&&<a className="button" href={'/api/papers/'+id+'/pdf'} target="_blank" rel="noreferrer"><Download size={15}/>另存 PDF</a>}</div></div>
 {error&&<div className="alert" role="alert">{error}</div>}
 <div className="reading-grid"><section className="document-pane"><div className="row pdf-search"><input placeholder="搜索全文关键词" aria-label="搜索全文关键词" value={find} onChange={e=>{setFind(e.target.value);setFindPages((paper.pages||[]).filter(p=>p.text.toLowerCase().includes(e.target.value.toLowerCase())).map(p=>p.page));}}/>{find&&<select aria-label="搜索结果页" onChange={e=>setPage(Number(e.target.value))}><option value={page}>命中 {findPages.length} 页</option>{findPages.map(n=><option key={n} value={n}>第 {n} 页</option>)}</select>}{outline.length>0&&<select aria-label="论文目录" value={page} onChange={e=>setPage(Number(e.target.value))}><option value={page}>章节目录</option>{outline.map((o,i)=><option key={i} value={o.page}>{o.title}</option>)}</select>}</div>
 {!paper.pdf_file?<div className="empty"><BookOpen size={36}/><h3>保存全文，开始阅读</h3><p>论文 PDF 会保存在本机，可离线打开。</p><div className="row"><button className="primary" disabled={!!busy||!paper.pdf_url} onClick={()=>action('download',async()=>{await api('/papers/'+id+'/download','POST');await refresh();})}>{busy==='download'?'下载中…':'获取开放 PDF'}</button><label className="button">上传 PDF<input type="file" accept=".pdf" hidden onChange={e=>{const f=e.target.files?.[0];if(f)action('upload',async()=>{const fd=new FormData();fd.append('file',f);await api('/import/pdf?paper_id='+id,'POST',fd);await refresh();});}}/></label>{paper.url&&<a href={safeUrl(paper.url)} target="_blank" rel="noreferrer">论文来源 ↗</a>}</div><p className="muted">只有摘要时，AI 也可以生成简短概览。</p></div>:<><div className="pdf-scroll"><div className="pdf-box" ref={box} onMouseUp={selected} onTouchEnd={selected}>{textMode?<div className="extracted">{paper.pages?.find(p=>p.page===page)?.text||'此页无可提取文字，需要 OCR。'}</div>:<div className="pdf-page" style={{width:width*zoom}}><canvas ref={canvas}/><div className="textLayer" ref={layer}/><div className="highlight-layer">{notes.filter(n=>n.page===page&&n.file_hash===paper.pdf_hash).flatMap(n=>n.rects.map((r,i)=><span key={n.id+i} style={{left:r.x*100+'%',top:r.y*100+'%',width:r.w*100+'%',height:r.h*100+'%'}}/>))}</div></div>}</div></div><div className="muted caption">选中文字可翻译、解释或高亮保存。{paper.scanned?' 此文件为扫描件或文字提取不足，需先 OCR。':''}{paper.pdf_version&&paper.version!==paper.pdf_version?' 已保存 PDF 与最新元数据版本不同，可重新下载更新。':''}</div></>}
 {quote&&<div className="selection-tools"><div className="selection-quote">“{quote.slice(0,140)}{quote.length>140?'…':''}”</div><div className="row"><button disabled={!!busy} onClick={()=>ask('translate',quote)}><Languages size={15}/>翻译</button><button disabled={!!busy} onClick={()=>ask('explain',quote)}><MessageCircle size={15}/>解释</button><button disabled={!!busy} onClick={saveNote}><Highlighter size={15}/>高亮保存</button><button onClick={()=>{setTab('notes');}}><NotebookPen size={15}/>记笔记</button><button className="text-button" onClick={()=>setQuote('')}>取消</button></div></div>}
 </section><aside className="assistant-pane"><div className="tabs">{[['summary','AI 解读'],['chat','翻译 / 问答'],['notes',`笔记 ${notes.length}`]].map(([key,label])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{label}</button>)}</div>
 {busy&&<div className="busy"><LoaderCircle className="spin" size={16}/>正在处理，请稍候…</div>}
 {tab==='summary'&&<><div className="row"><button disabled={!!busy} className="primary" onClick={()=>action('summary',async()=>{await api('/papers/'+id+'/summary','POST',{direction_id:directionId});await refresh();})}>生成概览</button><button disabled={!!busy||!paper.pdf_file} onClick={()=>action('deep',async()=>{await api('/papers/'+id+'/summary','POST',{deep:true,direction_id:directionId});await refresh();})}>深入解读</button></div>{paper.deep_summary?summaryText(paper.deep_summary):paper.summary?summaryText(paper.summary):<div className="assistant-empty"><h3>从问题、方法到结论</h3><p>配置模型后，生成有原文依据的中文概览。尚未生成时保留作者摘要。</p><div className="abstract">{paper.abstract||paper.curation||'暂无摘要，可在论文详情中更新元数据。'}</div></div>}<div className="prerequisites"><h3>补充前置知识</h3><div className="tags">{paper.tags.slice(0,6).map(t=><button key={t} onClick={()=>courses(t)}>{t} ↗</button>)}</div><button className="text-button" disabled={!!busy} onClick={()=>ask('concepts','这篇论文需要哪些前置知识？')}>让 AI 梳理前置知识</button></div></>}
 {tab==='chat'&&<><p className="muted">问答依据当前页及选文；翻译结果会缓存。</p>{answer?summaryText(answer):<div className="assistant-empty"><Languages size={28}/><h3>读到不懂的地方，就在这里问。</h3><p>选中左侧文字后点击翻译，或输入对当前页的问题。</p></div>}<form onSubmit={e=>{e.preventDefault();ask('question',question);}}><textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder="这一页的方法为什么有效？" aria-label="论文问题"/><button className="primary" disabled={!!busy||!question.trim()}>发送问题</button></form></>}
 {tab==='notes'&&<><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder={quote?'为选中的段落添加笔记…':'记录你的理解、疑问或实验想法…'} aria-label="阅读笔记"/><button className="primary" disabled={!!busy||(!note.trim()&&!quote)} onClick={saveNote}>保存笔记</button><div className="note-list">{notes.map(n=><article className="note" key={n.id}><div className="row spread"><button className="text-button" onClick={()=>setPage(n.page||1)}>第 {n.page||1} 页 ↗</button><button className="text-button danger" onClick={()=>action('delete-note',async()=>{await api('/notes/'+n.id,'DELETE');await refresh();})}>删除</button></div>{n.quote&&<blockquote>{n.quote}</blockquote>}<p>{n.text}</p><small>{new Date(n.created).toLocaleDateString()}{n.file_hash!==paper.pdf_hash?' · 其他版本笔记':''}</small></article>)}</div></>}
 </aside></div></div>;
}
