import {useEffect,useState} from 'react';
import {CheckCircle2,KeyRound,ExternalLink,Save,ShieldCheck,Database} from 'lucide-react';
import {api,safeUrl} from './api';
type Props={notify:(s:string)=>void;reload:()=>Promise<void>};
export default function Settings({notify,reload}:Props){
 const [data,setData]=useState<any>();const [selected,setSelected]=useState('deepseek');const [p,setP]=useState<any>({});const [s,setS]=useState<any>({});
 const [busy,setBusy]=useState('');const [error,setError]=useState('');const [collections,setCollections]=useState<{id:string;name:string}[]>([]);
 const [secret,setSecret]=useState({zotero_key:'',embedding_key:'',openalex_key:''});
 async function load(){const d=await api('/settings');setData(d);setS(d.settings);return d;}
 useEffect(()=>{load().then(d=>{setSelected(d.settings.active_provider);setP({...d.providers.find((x:any)=>x.id===d.settings.active_provider),api_key:''});}).catch(e=>setError(e.message));},[]);
 async function run(name:string,fn:()=>Promise<void>){setBusy(name);setError('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 async function saveGeneral(){await api('/settings','PUT',{...s,...secret});setSecret({zotero_key:'',embedding_key:'',openalex_key:''});await load();await reload();notify('设置已保存');}
 if(!data)return <div className="empty">{error||'加载设置…'}</div>;
 const field=(label:string,key:string,type='text',extra?:string)=><label className="field">{label}<input type={type} value={s[key]??''} onChange={e=>setS({...s,[key]:type==='number'?Number(e.target.value):e.target.value})}/>{extra&&<small>{extra}</small>}</label>;
 return <><div className="page-heading"><div><span className="eyebrow">PREFERENCES</span><h1>模型与设置</h1><p>配置一次，让获取、阅读和整理按你的习惯工作。</p></div><button className="primary" disabled={!!busy} onClick={()=>run('general',saveGeneral)}><Save size={17}/>保存通用设置</button></div>
 {error&&<div className="alert" role="alert">{error}</div>}
 <section className="settings-section"><div className="section-title"><KeyRound/><div><h2>AI 模型</h2><p>选择服务商，填写密钥。默认地址和模型可在高级配置中修改。</p></div></div>
 <div className="provider-grid">{data.providers.map((x:any)=><button key={x.id} className={'provider '+(selected===x.id?'selected':'')} onClick={()=>{setSelected(x.id);setP({...x,api_key:''});}}><span>{x.name}</span>{x.has_key&&<CheckCircle2 size={14}/>}</button>)}</div>
 <div className="settings-two"><div><label className="field">API Key<input aria-label="模型 API Key" autoComplete="off" type="password" value={p.api_key||''} onChange={e=>setP({...p,api_key:e.target.value})} placeholder={p.has_key?'已保存；留空则保持原密钥':'填写服务商开放平台密钥'}/><small>密钥只在本机后端加密保存，普通备份不包含密钥。</small></label><p className="muted">{p.help}</p>{p.docs&&<a className="inline-link" href={safeUrl(p.docs)} target="_blank" rel="noreferrer">官方接入说明 <ExternalLink size={13}/></a>}</div><div><label className="field">模型名称<input value={p.model||''} onChange={e=>setP({...p,model:e.target.value})}/><small>默认值是起点；以你的账户权限和官方可用模型为准。</small></label><label className="field">日常概览使用<select value={s.active_provider} onChange={e=>setS({...s,active_provider:e.target.value})}>{data.providers.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label></div></div>
 <details><summary>高级配置：接口、协议、地域与价格</summary><div className="settings-two"><label className="field">接口地址<input value={p.base_url||''} onChange={e=>setP({...p,base_url:e.target.value})}/>{selected==='qwen'&&<small>北京：https://dashscope.aliyuncs.com/compatible-mode/v1<br/>新加坡：https://dashscope-intl.aliyuncs.com/compatible-mode/v1</small>}</label><label className="field">接口协议<select value={p.protocol||'chat'} onChange={e=>setP({...p,protocol:e.target.value})}><option value="chat">OpenAI Chat 兼容</option><option value="responses">OpenAI Responses</option><option value="anthropic">Claude Messages</option><option value="gemini">Gemini 原生</option></select></label>{selected==='claude'&&<label className="field">工作区 ID（按需）<input value={p.workspace||''} onChange={e=>setP({...p,workspace:e.target.value})}/></label>}<label className="field">输入价格 / 百万 token（人民币）<input type="number" min="0" step="0.01" value={p.input_price??''} onChange={e=>setP({...p,input_price:e.target.value===''?null:Number(e.target.value)})}/></label><label className="field">输出价格 / 百万 token（人民币）<input type="number" min="0" step="0.01" value={p.output_price??''} onChange={e=>setP({...p,output_price:e.target.value===''?null:Number(e.target.value)})}/></label></div><p className="muted">费用仅按你填写的单价估算；不含缓存折扣等，最终以平台账单为准。</p></details>
 <div className="row"><button className="primary" disabled={!!busy} onClick={()=>run('provider',async()=>{await api('/providers/'+selected,'PUT',p);const d=await load();setP({...d.providers.find((x:any)=>x.id===selected),api_key:''});notify('模型配置已保存');})}>保存此模型配置</button><button disabled={!!busy} onClick={()=>run('test',async()=>{await api('/providers/'+selected,'PUT',p);const result=await api('/providers/'+selected+'/test','POST');await load();setP({...p,has_key:true,api_key:''});notify('连接成功：'+result.model);})}>{busy==='test'?'测试中…':'保存并测试连接'}</button>{p.has_key&&<button className="text-button danger" disabled={!!busy} onClick={()=>run('clear',async()=>{await api('/providers/'+selected,'PUT',{clear_key:true});const d=await load();setP({...d.providers.find((x:any)=>x.id===selected),api_key:''});notify('密钥已清除');})}>清除此密钥</button>}</div><small className="muted">连接测试会发起一次真实模型调用。</small>
 </section>
 <section className="settings-section"><div className="section-title"><ShieldCheck/><div><h2>推荐与用量</h2><p>先筛候选，再按需调用模型。数量上限不是推荐目标。</p></div></div><div className="settings-two">{field('每天最多推荐','daily_limit','number')}{field('新论文回看天数','lookback_days','number','每天重查最近几天，减少来源收录延迟造成的遗漏。')}<label className="field">全文解读使用<select value={s.deep_provider} onChange={e=>setS({...s,deep_provider:e.target.value})}><option value="">与日常概览相同</option>{data.providers.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>{field('每次 AI 精筛候选上限','ai_candidates','number')}{field('每天最多 AI 调用次数','daily_ai_calls','number')}{field('每日 token 上限','daily_token_limit','number')}</div><label className="check"><input type="checkbox" checked={s.auto_ai} onChange={e=>setS({...s,auto_ai:e.target.checked})}/>获取论文后自动进行 AI 精筛和摘要概览</label>
 <div className="usage-strip"><span>今日调用 <strong>{data.usage.length}</strong></span><span>记录 token <strong>{data.usage.reduce((n:number,u:any)=>n+(u.total_tokens||u.reserved||0),0).toLocaleString()}</strong></span><span>已计价调用估算 <strong>¥{data.usage.reduce((n:number,u:any)=>n+(u.cost||0),0).toFixed(4)}</strong></span></div><small className="muted">未设置单价的调用不计入费用估算；失败请求保留 token 预留估计。</small>
 <details><summary>可选：语义向量匹配</summary><label className="check"><input type="checkbox" checked={s.embedding_enabled} onChange={e=>setS({...s,embedding_enabled:e.target.checked})}/>启用独立向量模型，辅助候选相关性排序</label><div className="settings-two">{field('向量接口地址','embedding_url')}{field('向量模型','embedding_model')}<label className="field">向量模型 API Key<input type="password" autoComplete="off" value={secret.embedding_key} onChange={e=>setSecret({...secret,embedding_key:e.target.value})} placeholder={data.secrets.embedding_key?'已保存，留空保持不变':'OpenAI 兼容 embeddings 接口密钥'}/></label></div><p className="muted">未配置时使用关键词、分类与反馈。向量调用也受每日用量限制。</p></details></section>
 <section className="settings-section"><h2>自动更新与来源</h2><label className="check"><input type="checkbox" checked={s.schedule_enabled} onChange={e=>setS({...s,schedule_enabled:e.target.checked})}/>每日自动获取论文</label><div className="settings-two">{field('每天几点更新（0–23）','schedule_hour','number')}{field('时区','timezone')}<label className="field">OpenAlex API Key（可选）<input type="password" autoComplete="off" value={secret.openalex_key} onChange={e=>setSecret({...secret,openalex_key:e.target.value})} placeholder={data.secrets.openalex_key?'已保存，留空保持不变':'按 OpenAlex 账户的额度与权限配置'}/></label></div><p className="muted">本地版需要电脑开机且后台服务运行。启动时会补查当天尚未执行的更新。</p></section>
 <section className="settings-section"><h2>Zotero 文献库</h2><p className="muted">手动导入已有文献，或把论文、总结和笔记保存到个人文献库。</p><div className="settings-two"><label className="field">Zotero API Key<input type="password" autoComplete="off" value={secret.zotero_key} onChange={e=>setSecret({...secret,zotero_key:e.target.value})} placeholder={data.secrets.zotero_key?'已保存，留空保持不变':'需要个人文献库读写权限'}/><small><a href="https://www.zotero.org/settings/keys" target="_blank" rel="noreferrer">前往 Zotero 创建 Key ↗</a></small></label>{field('用户 ID（连接后自动填写）','zotero_user_id')}</div><div className="row"><button disabled={!!busy} onClick={()=>run('zotero-test',async()=>{await saveGeneral();const r=await api('/zotero/test','POST');setCollections(r.collections);await load();notify('已连接 Zotero：'+r.username);})}>{busy==='zotero-test'?'连接中…':'保存并连接 Zotero'}</button><select aria-label="Zotero 目标集合" value={s.zotero_collection} onChange={e=>setS({...s,zotero_collection:e.target.value})}><option value="">文献库根目录</option>{collections.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}{s.zotero_collection&&!collections.some(c=>c.id===s.zotero_collection)&&<option value={s.zotero_collection}>{s.zotero_collection}</option>}</select><button disabled={!!busy||!s.zotero_user_id} onClick={()=>run('zotero-import',async()=>{const r=await api('/zotero/import','POST',{collection:s.zotero_collection});notify(`已导入 ${r.imported} 篇，新增 ${r.added} 篇`);await reload();})}>导入该集合</button></div><label className="check"><input type="checkbox" checked={s.zotero_pdf} onChange={e=>setS({...s,zotero_pdf:e.target.checked})}/>保存到 Zotero 时，同时上传已下载的 PDF</label><p className="muted">附件占用 Zotero 存储空间。修改该选项后请保存通用设置。</p></section>
 <section className="settings-section"><div className="section-title"><Database/><div><h2>备份与迁移</h2><p>备份包含论文、PDF、笔记、研究方向和课程记录，排除 API 密钥。</p></div></div><div className="row"><a className="button" href="/api/backup">下载完整备份</a><label className="button">合并恢复备份<input type="file" accept=".zip" hidden onChange={e=>{const f=e.target.files?.[0];if(f)run('restore',async()=>{const fd=new FormData();fd.append('file',f);const r=await api('/restore','POST',fd);await reload();notify(r.message);});}}/></label><a className="button" href="/api/export/notes">导出笔记 Markdown</a></div><p className="muted">恢复会合并新记录，已有同编号记录保持不变。超过 250 MB 的备份可直接迁移 data 文件夹。</p></section>
 </>;
}
